version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run start
          name: run app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy if the build job has completed
          filters:
            branches:
              only: main # only deploy when on main
